update3

diff --git a/docker-compose.yml b/docker-compose.yml
--- a/docker-compose.yml
+++ b/docker-compose.yml
@@ -27,16 +27,24 @@ services:
     deploy:
       restart_policy:
         condition: on-failure
-    entrypoint: ["bash", "-c"]
-    command: ["bench set-config -g db_host $$DB_HOST; bench set-config -gp db_port $$DB_PORT;"]
+    entrypoint:
+      - bash
+      - -c
+    command:
+      - >
+        ls -1 apps > sites/apps.txt;
+        bench set-config -g db_host $$DB_HOST;
+        bench set-config -gp db_port $$DB_PORT;
+        bench set-config -g redis_cache "redis://$$REDIS_CACHE";
+        bench set-config -g redis_queue "redis://$$REDIS_QUEUE";
+        bench set-config -g redis_socketio "redis://$$REDIS_QUEUE";
+        bench set-config -gp socketio_port $$SOCKETIO_PORT;
     environment:
       DB_HOST: as0gs04wkc8o8k8ww44kkwgs  # Nom ou IP du conteneur MariaDB
-      DB_PORT: "3306"
-      MYSQL_ROOT_PASSWORD: admin
-      MARIADB_ROOT_PASSWORD: admin
-      DB_USER: root
-      DB_PASSWORD: admin
-      DB_NAME: erp_feature_cicd  # Base de données "erp_feature_cicd"
+      DB_PORT: "3306" 
+      REDIS_CACHE: redis-cache:6379
+      REDIS_QUEUE: redis-queue:6379
+      SOCKETIO_PORT: "9000"
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -48,11 +56,27 @@ services:
     deploy:
       restart_policy:
         condition: on-failure
-    entrypoint: ["bash", "-c"]
-    command: ["wait-for-it -t 120 as0gs04wkc8o8k8ww44kkwgs:3306"]
-    volumes:
-      - sites:/home/frappe/frappe-bench/sites
-      - logs:/home/frappe/frappe-bench/logs
+    entrypoint: 
+      - bash 
+      - -c
+    command: 
+      - >
+        wait-for-it -t 120 as0gs04wkc8o8k8ww44kkwgs:3306
+        wait-for-it -t 120 redis-cache:6379;
+        wait-for-it -t 120 redis-queue:6379;
+        export start=`date +%s`;
+        until [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".db_host // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_cache // empty"` ]] && \
+          [[ -n `grep -hs ^ sites/common_site_config.json | jq -r ".redis_queue // empty"` ]];
+        do
+          echo "Waiting for sites/common_site_config.json to be created";
+          sleep 5;
+          if (( `date +%s`-start > 120 )); then
+            echo "could not find sites/common_site_config.json with required keys";
+            exit 1
+          fi
+        done;
+        echo "sites/common_site_config.json found";
 
   frontend:
     image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
@@ -63,9 +87,17 @@ services:
     deploy:
       restart_policy:
         condition: on-failure
-    command: ["nginx-entrypoint.sh"]
+    command: 
+      - nginx-entrypoint.sh
     environment:
       BACKEND: backend:8000
+      FRAPPE_SITE_NAME_HEADER: site1.local
+      SOCKETIO: websocket:9000
+      UPSTREAM_REAL_IP_ADDRESS: 127.0.0.1
+      UPSTREAM_REAL_IP_HEADER: X-Forwarded-For
+      UPSTREAM_REAL_IP_RECURSIVE: "off"
+      PROXY_READ_TIMEOUT: 120
+      CLIENT_MAX_BODY_SIZE: 50m
     volumes:
       - sites:/home/frappe/frappe-bench/sites
       - logs:/home/frappe/frappe-bench/logs
@@ -73,6 +105,38 @@ services:
       - "traefik.enable=true"
       - "traefik.http.routers.erpnext-feature-cicd.rule=Host(`cwo848sgsowsk04o40w4ckwg.161.97.174.134.sslip.io`)"
       - "traefik.http.services.erpnext-feature-cicd.loadbalancer.server.port=8080"
+
+  queue-long:
+    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
+    networks:
+      - coolify
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - long,default,short
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
+
+  queue-short:
+    image: ghcr.io/devofs2/pro_erpnext_feature-cicd:latest
+    networks:
+      - coolify
+    deploy:
+      restart_policy:
+        condition: on-failure
+    command:
+      - bench
+      - worker
+      - --queue
+      - short,default
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
 
   redis-queue:
     image: redis:6.2-alpine
@@ -111,12 +175,19 @@ services:
     deploy:
       restart_policy:
         condition: on-failure
-
-networks:
-  coolify:
-    external: true
+    command:
+      - node
+      - /home/frappe/frappe-bench/apps/frappe/socketio.js
+    volumes:
+      - sites:/home/frappe/frappe-bench/sites
+      - logs:/home/frappe/frappe-bench/logs
 
 volumes:
   sites:
   logs:
   redis-queue-data:
+
+networks:
+  coolify:
+    external: true
+
