check_deployment_status3

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -61,32 +61,42 @@ jobs:
       - name: Check app
         run: |
           APP_UUID=$(./.github/scripts/check_and_deploy.sh $COOLIFY_URL $PROJECT_UUID $BRANCH_NAME)
-          echo "APP_UUID=$APP_UUID" >> $GITHUB_ENV
-          echo "::set-output name=APP_UUID::$APP_UUID"
-  #        ./.github/scripts/check_and_deploy.sh $COOLIFY_URL $PROJECT_UUID $BRANCH_NAME
+          # Vérifier si APP_UUID est valide avant d'ajouter aux variables d'environnement
+          if [[ -n "$APP_UUID" && "$APP_UUID" != "null" ]]; then
+            echo "APP_UUID=$APP_UUID" >> $GITHUB_ENV
+            echo "APP_UUID=$APP_UUID" >> $GITHUB_OUTPUT
+            echo "✅ Application prête pour le déploiement : $APP_UUID"
+          else
+            echo "❌ Erreur : UUID invalide ou vide."
+            exit 1
+          fi
+        shell: bash
+  #         echo "APP_UUID=$APP_UUID" >> $GITHUB_ENV
+  #         echo "::set-output name=APP_UUID::$APP_UUID"
+  # #        ./.github/scripts/check_and_deploy.sh $COOLIFY_URL $PROJECT_UUID $BRANCH_NAME
 
 
-  track-deployment:
-    runs-on: ubuntu-latest
-    needs: deploy-app
-    steps:
-      - name: Checkout repository
-        uses: actions/checkout@v3
+  # track-deployment:
+  #   runs-on: ubuntu-latest
+  #   needs: deploy-app
+  #   steps:
+  #     - name: Checkout repository
+  #       uses: actions/checkout@v3
 
-      - name: Install jq
-        run: sudo apt-get install jq -y
+  #     - name: Install jq
+  #       run: sudo apt-get install jq -y
 
-      - name: Set execute permissions
-        run: |
-          chmod +x .github/scripts/check_deployment_status.sh
+  #     - name: Set execute permissions
+  #       run: |
+  #         chmod +x .github/scripts/check_deployment_status.sh
 
-      - name: Monitor Coolify Deployment
-        id: monitor
-        run: ./.github/scripts/check_deployment_status.sh $COOLIFY_URL $COOLIFY_API_KEY $APP_UUID
-        env:
-          COOLIFY_URL: https://coolify.ofs.bj
-          COOLIFY_API_KEY: 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f
-          APP_UUID: ${{ needs.deploy-app.outputs.APP_UUID }}
+  #     - name: Monitor Coolify Deployment
+  #       id: monitor
+  #       run: ./.github/scripts/check_deployment_status.sh $COOLIFY_URL $COOLIFY_API_KEY $APP_UUID
+  #       env:
+  #         COOLIFY_URL: https://coolify.ofs.bj
+  #         COOLIFY_API_KEY: 1|6rnyiYLZtJRXYwiyiVRv3m3ytr6GOGspcTKoC4HTa8e42f6f
+  #         APP_UUID: ${{ needs.deploy-app.outputs.APP_UUID }}
 
       # - name: Update GitHub Deployment Status (Success)
       #   if: env.deployment_status == 'success'
